### ISSUE TITLE
Debian keys?

### ISSUE THREAD

**Issue by breadtk** [rapid7/ssh-badkeys#8]
Originally @hmoore-r7 cataloged a variety of weak Debian keys on [DigitalOffense.net](http://digitaloffense.net/tools/debian-openssl/) (link is now dead). However a mirror remains in another Github repository here: [g0tmi1k/debian-ssh](https://github.com/g0tmi1k/debian-ssh). No license currently exists on g0tmi1k's repository besides a copyright notice for HD Moore's original contribution, so I think it should be fine to merge keys from that repo into this one. My thought being that private keys from that repo could be use to gain access to known authorized keys.

Thoughts?

**Comment by breadtk** [comment]
If there are no objections, I can go ahead and massage the data from g0tm1k's repo into a similar format found here.

**Comment by BenBE** [comment]
In the Kompromat project at https://github.com/BenBE/kompromat/tree/master/src/debian_openssl_weak_keys is a much more complete list. Due to the sheer size of it I'd not recommend adding them if not absolutely required. The pure number causes quite some ill effects I got complaints about :)

**Comment by hmoore-r7** [comment]
I don't think this project a good location for the Debian weak keys (due to the sheer number) and agree that Kompromat is a better fit right now.
